Project/Home/urls.py
from django.urls import path
from .views import home, courses, blog, blog_detail, concepts

app_name = "Home"
urlpatterns = [
    path('', home, name="Home"),
    path('courses', courses, name="Courses"),
    path('blog', blog),
    path('detail', blog_detail),
    path('concept/<subject_slug>/<grade_slug>/<topic_slug>/', concepts, name="Concepts"),
    ]

Project/Notes/urls.py
from django.urls import path
from .views import List_Notes, Note_View, Create_Note, Copy_Note, save_note, remove_note

app_name="Notes"

urlpatterns = [
    path('list', List_Notes, name="List"),
    path('view/<id>', Note_View,name="View"),
    path('create/', Create_Note,name="Create"),
    path('copy/<id>', Copy_Note,name="Copy"),
    path('save/<id>', save_note, name="Save"),
    path('remove/<id>', remove_note, name="Remove"),
    ]

Project/Profile/urls.py
from django.urls import path
from .views import register, Login, User_Profile, View_Profile, Retry_Login

app_name = "Profile"
urlpatterns = [
    path('register', register, name="Register"),
    path('login', Login, name="Login"),
    path('profile', User_Profile, name="Profile"),
    path('profile/<slug>', View_Profile, name="View"),
    path('retry/',Retry_Login,name="Retry"),
    ]

Project/Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls', namespace="Home")),
    path('profile/', include('Profile.urls', namespace="Profile")),
    path('notes/', include('Notes.urls', namespace="Notes")),
    path('save/', include('DefinitionsAndExplanations.urls', namespace='Definition')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Project/Profile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.urls import reverse
from Notes.models import Notes
from DefinitionsAndExplanations.models import Definition, Explanation, Videos


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    slug = models.SlugField()
    copied_notes = models.ManyToManyField(Notes, blank=True, related_name="Notes")
    saved_definitions = models.ManyToManyField(Definition,blank=True,related_name="Definitions")
    saved_explanations = models.ManyToManyField(Explanation,blank=True,related_name="Explanations")
    saved_videos = models.ManyToManyField(Videos,blank=True,related_name="Videos")
    
    
    def __str__(self):
        return str(self.user.username)

    def view_profile(self):
        return reverse('Profile:View',kwargs={"slug":self.slug})

def create_profile(sender, instance, created, *args, **kwargs):
    if created:
        try:
            Profile.objects.create(user=instance, slug=instance)
        except:
            pass
        
post_save.connect(create_profile, sender=User)

Project/Profile/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

Project/Profile/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Profile
from django.contrib.auth import get_user_model
from .forms import RegisterForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from Notes.models import Notes

def register(request):
    if request.method == "POST":
        print(request.POST)
        form = RegisterForm(request.POST)
        
        if form.is_valid():
            form.save()
            return redirect('Profile:Login')
        else:
            return redirect('Profile:Retry')
    
    return render(request, 'Profile/register.html')

def Login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user:
            login(request,user)
            return redirect('Profile:Profile')
    return render(request, 'Profile/login.html')

@login_required
def User_Profile(request):
    user = request.user

    saved_notes = user.profile.copied_notes.all()

    notes = Notes.objects.filter(user=user)

    definitions = user.profile.saved_definitions.all()

    explanations = user.profile.saved_explanations.all()

    videos = user.profile.saved_videos.all()

    context = {
        "user":user,
        "saved_notes":saved_notes,
        "notes":notes,
        "definitions":definitions,
        "explanations":explanations,
        "videos":videos,
        }

    
    return render(request, "Profile/Profile.html",context)


def View_Profile(request, slug):
    profile = Profile.objects.get(slug=slug)

    definitions = profile.saved_definitions.all()
    explanations = profile.saved_explanations.all()
    notes = Notes.objects.filter(user=profile.user,status="Pu")

    context = {
        "profile":profile,
        "definitions":definitions,
        "explanations":explanations,
        "notes":notes,
        }

    return render(request, "Profile/ViewProfile.html",context)

def Retry_Login(request):
    return render(request,"Profile/Retry_Login.html")

Project/Profile/templates/Profile/Profile.html
{% extends 'Home/header.html' %}

{% block content %}

{% include 'Home/head.html' %}

    <main>
        <!--? slider Area Start-->
        <section class="slider-area slider-area2">
            <div class="slider-active">
                <!-- Single Slider -->
                <div class="single-slider slider-height2">
                    <div class="container">
                        <div class="row">
                            <div class="col-xl-8 col-lg-11 col-md-12">
                                <div class="hero__caption hero__caption2">
                                    <h1 data-animation="bounceIn" data-delay="0.2s">Welcome {{ user.username }}</h1>
                                    <!-- breadcrumb Start-->
                                    <nav aria-label="breadcrumb">
                                        <ol class="breadcrumb">
                                            <li class="breadcrumb-item"><a href="{% url 'Home:Home' %}">Home</a></li>
                                            <li class="breadcrumb-item"><a href="{% url 'Notes:Create' %}">Create Your Notes</a></li> 
                                        </ol>
                                    </nav>
                                    <!-- breadcrumb End -->
                                </div>
                            </div>
                        </div>
                    </div>          
                </div>
            </div>
        </section>
        <!-- Courses area start -->
        <div class="courses-area section-padding40 fix">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-xl-7 col-lg-8">
                        <div class="section-tittle text-center mb-55">
                            <h2>Saved Definitions</h2>
                        </div>
                    </div>
                </div>
					{% for definition in definitions %}
					<article class="blog_item">
						<div class="blog_details">
							<a class="d-inline-block" href="/concept/{{ definition.concept.topic.grade.subject.slug }}/{{ definition.concept.topic.grade.slug }}/{{ definition.concept.topic.slug }}#{{ definition.term }}">
							<h2 class="blog-head" style="color: #2d2d2d;">{{ definition.term }}</h2>
							</a> 
							<!--<p>{{ explanation.explanation_for_concept }}<br>-->
							{% for term in definition.definitionsforterm %}
							<p>{{ term.definition_for_term }}</p>
							{% endfor %}
						<a href="{{ definition.remove_definition }}" class="genric-btn warning-border">Remove</a>							
						</div>
					</article>
					{% endfor %}
            </div>
			<div class="container">
                <div class="row justify-content-center">
                    <div class="col-xl-7 col-lg-8">
                        <div class="section-tittle text-center mb-55">
                            <h2>Saved Explanations</h2>
                        </div>
                    </div>
                </div>
					{% for explanation in explanations %}
						<article class="blog_item">
							<div class="blog_details">
								<a class="d-inline-block" href="/concept/{{ explanation.concept.topic.grade.subject.slug }}/{{ explanation.concept.topic.grade.slug }}/{{ explanation.concept.topic.slug }}#{{ explanation.title }}">
								<h2 class="blog-head" style="color: #2d2d2d;">{{ explanation.title }}</h2>
								</a>
								<!--<p>{{ explanation.explanation_for_concept }}<br>-->
								<p>{{ explanation.explanation_for_concept }}</p>
						<a href="{{ explanation.remove_explanation }}" class="genric-btn warning-border">Remove</a>	
							</div>
						</article>
					{% endfor %}
            </div>
			
			<div class="container">
                <div class="row justify-content-center">
                    <div class="col-xl-7 col-lg-8">
                        <div class="section-tittle text-center mb-55">
                            <h2>Your Notes</h2>
                        </div>
                    </div>
                </div>
					{% for note in notes %}
						<article class="blog_item">
							<div class="blog_details">
								<a class="d-inline-block" href="{{ note.view_note }}">
								<h2 class="blog-head" style="color: #2d2d2d;">{{ note.name }}</h2>
								</a>
								<p>{{ note.first_fifty_words }}...</p>
							</div>
						</article>
					{% endfor %}
            </div>
			
			<div class="container">
                <div class="row justify-content-center">
                    <div class="col-xl-7 col-lg-8">
                        <div class="section-tittle text-center mb-55">
                            <h2>Saved Notes</h2>
                        </div>
                    </div>
                </div>
					{% for saved_note in saved_notes %}
						<article class="blog_item">
							<div class="blog_details">
								<a class="d-inline-block" href="{{ saved_note.view_note }}">
								<h2 class="blog-head" style="color: #2d2d2d;">{{ saved_note.name }}</h2>
								</a>
								<p>{{ saved_note.first_fifty_words }}...</p>
								<p><a href="{{ saved_note.remove_note }}" class="genric-btn warning-border">Remove</a></p>
							</div>
						</article>
					{% endfor %}
            </div>
			
			<div class="container">
                <div class="row justify-content-center">
                    <div class="col-xl-7 col-lg-8">
                        <div class="section-tittle text-center mb-55">
                            <h2>Saved Videos</h2>
                        </div>
                    </div>
                </div>
					{% for video in videos %}
						<article class="blog_item">
							<div class="blog_details">
								<a class="d-inline-block" href="/concept/{{ video.topic.grade.subject.slug }}/{{  video.topic.grade.slug}}/{{ video.topic.slug }}#{{ video.title }}">
								<h2 class="blog-head" style="color: #2d2d2d;">{{ video.title }}</h2>
								</a>
								<p><a href="{{ video.remove_video }}" class="genric-btn warning-border">Remove</a></p>
							</div>
						</article>
					{% endfor %}
            </div>
        </div>
    </main>
	
{% endblock %}

Project/Profile/templates/Profile/Retry_Login.html
{% extends 'Home/header.html' %}



{% block content %}

{% include 'Home/head.html' %}

   <section class="slider-area slider-area2">
     <div class="slider-active">
       <!-- Single Slider -->
       <div class="single-slider slider-height2">
         <div class="container">
           <div class="row">
             <div class="col-xl-8 col-lg-11 col-md-12">
               <div class="hero__caption hero__caption2">
                 <h1 data-animation="bounceIn" data-delay="0.2s"><a href="{% url 'Profile:Register' %}">Retry Register</a></h1>
                 <!-- breadcrumb Start-->
                 <nav aria-label="breadcrumb">
                   <ol class="breadcrumb">
                     <li class="breadcrumb-item"><a href="{% url 'Profile:Register' %}">Register</a></li>
                     <li class="breadcrumb-item"><a href="{% url 'Profile:Login' %}">Login</a></li> 
                  </ol>
               </nav>
               <!-- breadcrumb End -->
            </div>
         </div>
      </div>
   </div>          
</div>
</div>
</section>

{% endblock %}

Project/Profile/templates/Profile/ViewProfile.html
{% extends 'Home/header.html' %}

{% block content %}

{% include 'Home/head.html' %}

    <main>
        <!--? slider Area Start-->
        <section class="slider-area slider-area2">
            <div class="slider-active">
                <!-- Single Slider -->
                <div class="single-slider slider-height2">
                    <div class="container">
                            <div class="col-xl-8 col-lg-11 col-md-12">
                                <div class="hero__caption hero__caption2">
                                    <h1 data-animation="bounceIn" data-delay="0.2s">{{ profile.user.username }}'s Profile</h1>
                                    <!-- breadcrumb Start-->
                                    <nav aria-label="breadcrumb">
                                        <ol class="breadcrumb">
                                            <li class="breadcrumb-item"><a href="{% url 'Home:Home' %}">Home</a></li>
                                            <li class="breadcrumb-item"><a href="{% url 'Profile:Profile' %}">Your Own Profile</a></li> 
                                        </ol>
                                    </nav>
                                    <!-- breadcrumb End -->
                                </div>
                            </div>
                        </div>
                    </div>          
                </div>
        </section>
        <!-- Courses area start -->
        <div class="courses-area section-padding40 fix">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-xl-7 col-lg-8">
                        <div class="section-tittle text-center mb-55">
                            <h2>Saved Definitions</h2>
                        </div>
                    </div>
                </div>
				{% for definition in definitions %}
					<article class="blog_item">
						<div class="blog_details">
							<a class="d-inline-block" href="/concept/{{ definition.concept.topic.grade.subject.slug }}/{{ definition.concept.topic.grade.slug }}/{{ definition.concept.topic.slug }}#{{ definition.term }}">
							<h2 class="blog-head" style="color: #2d2d2d;">{{ definition.term }}</h2>
							</a>
							<!--<p>{{ explanation.explanation_for_concept }}<br>-->
							<p><a href="#">More examples of physical quantities>></a></p>
						</div>
					</article>
				{% endfor %}
				</div>
            </div>
			<div class="container">
                <div class="row justify-content-center">
                    <div class="col-xl-7 col-lg-8">
                        <div class="section-tittle text-center mb-55">
                            <h2>Saved Explanations</h2>
                        </div>
                    </div>
                </div>
					{% for explanation in explanations %}
						<article class="blog_item">
							<div class="blog_details">
								<a class="d-inline-block" href="/concept/{{ explanation.concept.topic.grade.subject.slug }}/{{ explanation.concept.topic.grade.slug }}/{{ explanation.concept.topic.slug }}#{{ explanation.title }}">
								<h2 class="blog-head" style="color: #2d2d2d;">{{ explanation.title }}</h2>
								</a>
								<!--<p>{{ explanation.explanation_for_concept }}<br>-->
								<p>{{ explanation.explanation_for_concept }}</p>
							</div>
						</article>
					{% endfor %}
				</div>
            </div>
			
			<div class="container">
                <div class="row justify-content-center">
                    <div class="col-xl-7 col-lg-8">
                        <div class="section-tittle text-center mb-55">
                            <h2>{{ profile.user.username }}'s Notes</h2>
                        </div>
                    </div>
                </div>
					{% for note in notes %}
						<article class="blog_item">
							<div class="blog_details">
								<a class="d-inline-block" href="{{ note.view_note }}">
								<h2 class="blog-head" style="color: #2d2d2d;">{{ note.name }}</h2>
								</a>
								<p>{{ note.first_fifty_words }}...<br><a href="#">More</a></p><!-- First ten words -->
							</div>
						</article>
					{% endfor %}
            </div>
        </div>
    </main>
	
{% endblock %}

Project/Profile/templates/Profile/form_header.html
<!doctype html>
<html class="no-js" lang="zxx">
<head>
	{% load static %}
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>HloniSite</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/x-icon" href="/media/img/favicon.ico">
	
	
    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/slicknav.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/progressbar_barfiller.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/gijgo.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/animated-headline.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome-all.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
</head>
<body>
<!-- Register -->

<main class="login-body">
    <!-- Login Admin -->
    <form class="form-default" method="POST">
        
        <div class="login-form">
            <!-- logo-login -->
            <div class="logo-login">
                <a href="index.html"><img src="/media/img/logo/loder.png" alt=""></a>
            </div>
			
			{% csrf_token %}

            {% block content %}
			{% endblock %}
			
			
        </div>
    </form>
    <!-- /end login form -->
</main>


<!-- JS here -->
<script src="{% static './assets/js/vendor/modernizr-3.5.0.min.js' %}"></script>
<!-- Jquery, Popper, Bootstrap -->
<script src="{% static './assets/js/vendor/jquery-1.12.4.min.js' %}"></script>
<script src="{% static './assets/js/popper.min.js' %}"></script>
<script src="{% static './assets/js/bootstrap.min.js' %}"></script>
<!-- Jquery Mobile Menu -->
<script src="{% static './assets/js/jquery.slicknav.min.js' %}"></script>

<!-- Jquery Slick , Owl-Carousel Plugins -->
<script src="{% static './assets/js/owl.carousel.min.js' %}"></script>
<script src="{% static './assets/js/slick.min.js' %}"></script>
<!-- One Page, Animated-HeadLin -->
<script src="{% static './assets/js/wow.min.js' %}"></script>
<script src="{% static './assets/js/animated.headline.js' %}"></script>
<script src="{% static './assets/js/jquery.magnific-popup.js' %}"></script>

<!-- Date Picker -->
<script src="{% static './assets/js/gijgo.min.js' %}"></script>
<!-- Nice-select, sticky -->
<script src="{% static './assets/js/jquery.nice-select.min.js' %}"></script>
<script src="{% static './assets/js/jquery.sticky.js' %}"></script>
<!-- Progress -->
<script src="{% static './assets/js/jquery.barfiller.js' %}"></script>

<!-- counter , waypoint,Hover Direction -->
<script src="{% static './assets/js/jquery.counterup.min.js' %}"></script>
<script src="{% static './assets/js/waypoints.min.js' %}"></script>
<script src="{% static './assets/js/jquery.countdown.min.js' %}"></script>
<script src="{% static './assets/js/hover-direction-snake.min.js' %}"></script>

<!-- contact js -->
<script src="{% static './assets/js/contact.js' %}"></script>
<script src="{% static './assets/js/jquery.form.js' %}"></script>
<script src="{% static './assets/js/jquery.validate.min.js' %}"></script>
<script src="{% static './assets/js/mail-script.js' %}"></script>
<script src="{% static './assets/js/jquery.ajaxchimp.min.js' %}"></script>

<!-- Jquery Plugins, main Jquery -->	
<script src="{% static './assets/js/plugins.js' %}"></script>
<script src="{% static './assets/js/main.js' %}"></script>
</html>

Project/Profile/templates/Profile/login.html
{% extends 'Profile/form_header.html' %}

{% block content %}

                <h2>Login Here</h2>
                <div class="form-input">
                    <label for="name">Username</label>
                    <input  type="text" name="username" placeholder="Username">
                </div>
                <div class="form-input">
                    <label for="name">Password</label>
                    <input type="password" name="password" placeholder="Password">
                </div>
                <div class="form-input pt-30">
                    <input type="submit" name="submit" value="login">
                </div>
                
                <!-- Forget Password -->
                <!-- Forget Password -->
                <a href="{% url 'Profile:Register' %}" class="registration">Join</a>

{% endblock %}

Project/Profile/templates/Profile/register.html
{% extends 'Profile/form_header.html' %}

{% block content %}

            <h2>Register Here</h2>
			
            <div class="form-input">
                <label for="name">Full name</label>
                <input  type="text" name="username" placeholder="Full name" maxlength="100">
            </div>
            <div class="form-input">
                <label for="name">Password</label>
                <input type="password" name="password1" placeholder="Password">
            </div>
            <div class="form-input">
                <label for="name">Confirm Password</label>
                <input type="password" name="password2" placeholder="Confirm Password">
            </div>
            <div class="form-input pt-30">
                <input type="submit" name="submit" value="Registration">
            </div>
            <!-- Forget Password -->
            <a href="{% url 'Profile:Login' %}" class="registration">login</a>

{% endblock %}