Project/Home/urls.py
from django.urls import path
from .views import home, courses, blog, blog_detail, concepts

app_name = "Home"
urlpatterns = [
    path('', home, name="Home"),
    path('courses', courses, name="Courses"),
    path('blog', blog),
    path('detail', blog_detail),
    path('concept/<subject_slug>/<grade_slug>/<topic_slug>/', concepts, name="Concepts"),
    ]

Project/Notes/urls.py
from django.urls import path
from .views import List_Notes, Note_View, Create_Note, Copy_Note, save_note, remove_note

app_name="Notes"

urlpatterns = [
    path('list', List_Notes, name="List"),
    path('view/<id>', Note_View,name="View"),
    path('create/', Create_Note,name="Create"),
    path('copy/<id>', Copy_Note,name="Copy"),
    path('save/<id>', save_note, name="Save"),
    path('remove/<id>', remove_note, name="Remove"),
    ]

Project/Profile/urls.py
from django.urls import path
from .views import register, Login, User_Profile, View_Profile, Retry_Login

app_name = "Profile"
urlpatterns = [
    path('register', register, name="Register"),
    path('login', Login, name="Login"),
    path('profile', User_Profile, name="Profile"),
    path('profile/<slug>', View_Profile, name="View"),
    path('retry/',Retry_Login,name="Retry"),
    ]

Project/Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls', namespace="Home")),
    path('profile/', include('Profile.urls', namespace="Profile")),
    path('notes/', include('Notes.urls', namespace="Notes")),
    path('save/', include('DefinitionsAndExplanations.urls', namespace='Definition')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Project/Home/models.py
from django.db import models
from django.urls import reverse


class Subject(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    
    def __str__(self):
        return self.title

    @property
    def grades(self):
        return self.grade_set.all()

class Grade(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, default=None)
    image_url = models.CharField(max_length=100,default=None,blank=True)
    
    def __str__(self):
        return self.title

    @property
    def topics(self):
        return self.topic_set.all()


class Topic(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    grade = models.ForeignKey(Grade, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title

    @property
    def concepts(self):
        return self.concept_set.all()

    @property
    def videos(self):
        return self.videos_set.all()

    def my_url(self):
        return reverse('Home:Concepts', kwargs={'subject_slug':self.grade.subject.slug, 'grade_slug':self.grade.slug, 'topic_slug':self.slug})

class Concept(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, default=None)
    
    def __str__(self):
        return self.title

    @property
    def explanations(self):
        return self.explanation_set.all()

    @property
    def definitions(self):
        return self.definition_set.all()

Project/Home/views.py
from django.shortcuts import render, redirect
from .models import Subject, Grade, Topic, Concept
from django.db.models import Q
from DefinitionsAndExplanations.models import Definition, Explanation, Videos


def home(request):
    subjects = Subject.objects.all()

    grades = Grade.objects.all()

    topics = Topic.objects.all()

    context = {
        "subjects":subjects,
        "topics":topics,
        "grades":grades,
        }
    
    return render(request, "Home/home.html", context)

def concepts(request, subject_slug, grade_slug, topic_slug):
    definitions = None
    explanations = None
    videos = None
    if request.GET:
        query = request.GET.get('search')
        definitions = Definition.objects.filter(Q(term__icontains=query))
        explanations = Explanation.objects.filter(Q(title__icontains=query))
        videos = Videos.objects.filter(Q(title__icontains=query))
    subject_q = Subject.objects.filter(slug=subject_slug)
    if subject_q.exists():
        subject = subject_q.first()
    else:
        return redirect("Home:Home")
        
    grade_q = subject.grades.filter(slug=grade_slug)
    if grade_q.exists():
        grade = grade_q.first()
    else:
        grade = None
        
    topic_q = grade.topics.filter(slug=topic_slug)
    if topic_q.exists():
        topic = topic_q.first()
    else:
        topic = None
        
    concepts = Concept.objects.filter(topic=topic)

    topics = Topic.objects.all()
        
    context = {
        'grade':grade,
        'topic':topic,
        'concepts':concepts,
        'topics':topics,
        'definitions':definitions,
        'explanations':explanations,
        'videos':videos,
    }
    
    return render(request, 'Home/concepts.html', context)
    


def courses(request):

    subjects = Subject.objects.all()

    context = {
        "subjects":subjects,
        }
    
    return render(request, "Home/courses.html", context)


def blog(request):
    return render(request, "Home/blog.html")


def blog_detail(request):
    return render(request, "Home/blog_details.html")

Project/Home/templates/Home/concepts.html
{% extends 'Home/header.html' %}

{% block content %}

{% include 'Home/head.html' %}

    <main>
        <!--? slider Area Start-->
        <section class="slider-area slider-area2">
            <div class="slider-active">
                <!-- Single Slider -->
                <div class="single-slider slider-height2">
                    <div class="container">
                        <div class="row">
                            <div class="col-xl-8 col-lg-11 col-md-12">
                                <div class="hero__caption hero__caption2">
                                    <h1 data-animation="bounceIn" data-delay="0.2s">{{ topic.title }}</h1>
                                    <!-- breadcrumb Start-->
                                    <nav aria-label="breadcrumb">
                                        <ol class="breadcrumb">
                                            <li class="breadcrumb-item"><a href="{% url 'Home:Home' %}">Home</a></li>
                                            <li class="breadcrumb-item"><a href="{% url 'Notes:Create' %}">Create Your Own Note</a></li> 
                                        </ol>
                                    </nav>
                                    <!-- breadcrumb End -->
                                </div>
                            </div>
                        </div>
                    </div>          
                </div>
            </div>
        </section>
        <!--? Blog Area Start-->
        <section class="blog_area section-padding">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 mb-5 mb-lg-0">
                        <div class="blog_left_sidebar">
							{% for concept in concepts %}
								<h1>{{ concept.title }}</h1>
								<div><br></div>
								<h3>Definitions</h3>
									{% for definition in concept.definitions %}
										{% if definitions != None %}
											{% if definition in definitions %}
												<article class="blog_item">
													<div class="blog_details">
														<h2 class="blog-head" style="color: #2d2d2d;" id="{{ definition.term }}">{{ definition.term }}</h2>
														{% for term in definition.definitionsforterm %}
														<p>{{ term.definition_for_term|linebreaks }}</p>
														{% endfor %}
													<a href="{{ definition.save_definition }}" class="genric-btn primary-border">Save</a>
													</div>
												</article>
											{% endif %}
										{% else %}
											<article class="blog_item">
												<div class="blog_details">
													<h2 class="blog-head" style="color: #2d2d2d;" id="{{ definition.term }}">{{ definition.term }}</h2>
													{% for term in definition.definitionsforterm %}
													<p>{{ term.definition_for_term|linebreaks }}</p>
													{% endfor %}
												<a href="{{ definition.save_definition }}" class="genric-btn primary-border">Save</a>
												</div>
											</article>
										{% endif %}
									{% endfor %}
								<h3>What to know</h3>
								{% for explanation in concept.explanations %}
									{% if explanations != None %}
										{% if explanation in explanations %}
											<article class="blog_item">
												<div class="blog_details">
													<h2 class="blog-head" style="color: #2d2d2d;" id="{{ explanation.title }}">{{ explanation.title }}</h2>
													<p>{{ explanation.explanation_for_concept|linebreaks }}</p>
													{% for link in explanation.explanationlinks %}
													<p><a href="{{ link.links }}" target="_blank">Click For {{ link.title }}</a><br>
													{% endfor %}
													</p>
												<a href="{{ explanation.save_explanation }}" class="genric-btn primary-border">Save</a>
												</div>
											</article>
										{% endif %}
									{% else %}
										<article class="blog_item">
											<div class="blog_details">
												<h2 class="blog-head" style="color: #2d2d2d;" id="{{ explanation.title }}">{{ explanation.title }}</h2>
												<p>{{ explanation.explanation_for_concept|linebreaks }}</p>
												{% for link in explanation.explanationlinks %}
												<p><a href="{{ link.links }}" target="_blank">Click For {{ link.title }}</a><br>
												{% endfor %}
												</p>
											<a href="{{ explanation.save_explanation }}" class="genric-btn primary-border">Save</a>
											</div>
										</article>
									
									{% endif %}
							{% endfor %}
							{% endfor %}
							<div><br></div>
							
							<h1>Videos</h1>
								<div><br></div>
								{% for video in topic.videos %}
									{% if videos != None %}
										{% if video in videos %}
											<article class="blog_item">
												<div class="blog_details">
													<a class="d-inline-block" href="{{ video.links }}" target="_blank">
													<h2 class="blog-head" style="color: #2d2d2d;" id="{{ video.title }}">{{ video.title }}</h2>
													</a>
													<p><a href="{{ video.save_video }}" class="genric-btn primary-border">Save</a></p>
												</div>
											</article>
										{% endif %}
									{% else %}
										<article class="blog_item">
											<div class="blog_details">
												<a class="d-inline-block" href="{{ video.links }}" target="_blank">
												<h2 class="blog-head" style="color: #2d2d2d;" id="{{ video.title }}">{{ video.title }}</h2>
												</a>
												<p><a href="{{ video.save_video }}" class="genric-btn primary-border">Save</a></p>
											</div>
										</article>
									{% endif %}
								{% endfor %}
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="blog_right_sidebar">
                            <aside class="single_sidebar_widget search_widget">
                                <form method="GET">
                                    <div class="form-group">
                                        <div class="input-group mb-3">
                                            <input type="text" name="search" class="form-control" placeholder='Search Keyword'
                                            onfocus="this.placeholder = ''"
                                            onblur="this.placeholder = 'Search Keyword'">
                                            <div class="input-group-append">
                                                <button class="btns" type="button"><i class="ti-search"></i></button>
                                            </div>
                                        </div>
                                    </div>
                                    <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
                                    type="submit">Search</button>
                                </form>
                            </aside>
                            <aside class="single_sidebar_widget post_category_widget">
                                <h4 class="widget_title" style="color: #2d2d2d;">Concepts</h4>
                                <ul class="list cat-list">
								{% for topic in topics %}
									{% if topic.grade == grade %}
                                    <li>
                                        <a href="{{ topic.my_url }}" class="d-flex">
                                            <p>{{ topic.title }}</p>
                                        </a>
                                    </li>
									{% endif %}
								{% endfor %}
                                </ul>
                            </aside>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Blog Area End -->
    </main>
{% endblock %}

Project/Home/templates/Home/courses.html
{% extends 'Home/header.html' %}

{% block content %}

{% include 'Home/head.html' %}

    <main>
        <!--? slider Area Start-->
        <section class="slider-area slider-area2">
            <div class="slider-active">
                <!-- Single Slider -->
                <div class="single-slider slider-height2">
                    <div class="container">
                        <div class="row">
                            <div class="col-xl-8 col-lg-11 col-md-12">
                                <div class="hero__caption hero__caption2">
                                    <h1 data-animation="bounceIn" data-delay="0.2s">Courses</h1>
                                    <!-- breadcrumb Start-->
                                    <nav aria-label="breadcrumb">
                                        <ol class="breadcrumb">
                                            <li class="breadcrumb-item"><a href="{% url 'Home:Home' %}">Home</a></li>
                                            <li class="breadcrumb-item"><a href="{% url 'Notes:List' %}">Notes</a></li> 
                                        </ol>
                                    </nav>
                                    <!-- breadcrumb End -->
                                </div>
                            </div>
                        </div>
                    </div>          
                </div>
            </div>
        </section>
        <!-- Courses area start -->
		{% for subject in subjects %}
        <div class="courses-area section-padding40 fix">
            <div class="container">
				<div class="row justify-content-center">
					<div class="col-xl-7 col-lg-8">
						<div class="section-tittle text-center mb-55">
							<h2>{{ subject.title }} Courses</h2>
						</div>
					</div>
				</div>
                <div class="courses-actives">
						{% for grade in subject.grades %}
						<div class="properties pb-20">
							<div class="properties__card">
								<div class="properties__img overlay1">
									<a href="#"><img src="{{ grade.image_url }}" alt=""></a>
								</div>
								<div class="properties__caption">
									<p>{{ grade.title }}</p>
										{% for topic in grade.topics %}
										<h3><a href="{{ topic.my_url }}">{{ topic.title }}</a></h3>
										<br>
										{% endfor %}
								</div>
							</div>
						</div>
						{% endfor %}
					 </div>
                </div>
            </div>
			{% endfor %}
        <!-- Courses area End -->
        <!--? top subjects Area Start -->
        <!-- top subjects End -->  
        <!-- ? services-area -->
    </main>
	
{% endblock %}

Project/Home/templates/Home/head.html
{% block content %}

    <header>
        <!-- Header Start -->
        <div class="header-area header-transparent">
            <div class="main-header ">
                <div class="header-bottom  header-sticky">
                    <div class="container-fluid">
                        <div class="row align-items-center">
                            <!-- Logo -->
                            <div class="col-xl-2 col-lg-2">
                                <div class="logo">
                                    <a href="{% url 'Home:Home' %}"><img src="/media/img/logo/logo.png" alt=""></a>
                                </div>
                            </div>
                            <div class="col-xl-10 col-lg-10">
                                <div class="menu-wrapper d-flex align-items-center justify-content-end">
                                    <!-- Main-menu -->
                                    <div class="main-menu d-none d-lg-block">
                                        <nav>
                                            <ul id="navigation">                                                                                          
                                                <li class="active" ><a href="{% url 'Home:Home' %}">Home</a></li>
                                                <li><a href="{% url 'Home:Courses' %}">Courses</a></li>
                                                <li><a href="{% url 'Notes:List' %}">Notes</a></li>
                                                <li><a href="{% url 'Profile:Profile' %}">Profile</a></li>
                                                <!-- Button -->
                                                <li class="button-header margin-left "><a href="{% url 'Profile:Register' %}" class="btn">Join</a></li>
                                                <li class="button-header"><a href="{% url 'Profile:Login' %}" class="btn btn3">Log in</a></li>
                                            </ul>
                                        </nav>
                                    </div>
                                </div>
                            </div> 
                            <!-- Mobile Menu -->
                            <div class="col-12">
                                <div class="mobile_menu d-block d-lg-none"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Header End -->
    </header>

{% endblock %}

Project/Home/templates/Home/home.html
{% extends 'Home/header.html' %}

{% block content %}

{% include 'Home/head.html' %}
    <main>
        <section class="slider-area ">
            <div class="slider-active">
                <div class="single-slider slider-height d-flex align-items-center">
                    <div class="container">
                        <div class="row">
                            <div class="col-xl-6 col-lg-7 col-md-12">
                                <div class="hero__caption">
                                    <h1 data-animation="fadeInLeft" data-delay="0.2s">Online Study<br> Guide</h1>
                                    <p data-animation="fadeInLeft" data-delay="0.4s">Find key concepts to study in the curriculum.<br> Use videos and additional resources to simplify things.<br> Read and write notes by other users<br></p>
                                    <a href="{% url 'Profile:Register' %}" class="btn hero-btn" data-animation="fadeInLeft" data-delay="0.7s">Join for Free</a>
                                </div>
                            </div>
                        </div>
                    </div>          
                </div>
            </div>
        </section>
        <div class="services-area">
            <div class="container">
                <div class="row justify-content-sm-center">
                    <div class="col-lg-4 col-md-6 col-sm-8">
                        <div class="single-services mb-30">
                            <div class="features-icon">
                                <img src="/media/img/icon/icon1.svg" alt="">
                            </div>
                            <div class="features-caption">
                                <h3>Study Guides</h3>
                                <p>Online study guides for high school courses</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-8">
                        <div class="single-services mb-30">
                            <div class="features-icon">
                                <img src="/media/img/icon/icon2.svg" alt="">
                            </div>
                            <div class="features-caption">
                                <h3>Videos And Sites</h3>
                                <p>Find the best videos and websites to simplify key concepts</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-8">
                        <div class="single-services mb-30">
                            <div class="features-icon">
                                <img src="/media/img/icon/icon3.svg" alt="">
                            </div>
                            <div class="features-caption">
                                <h3>Notes</h3>
                                <p>Find notes written by other users to make concepts easier</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
		
		{% for subject in subjects %}
        <div class="courses-area section-padding40 fix">
            <div class="container">
				<div class="row justify-content-center">
					<div class="col-xl-7 col-lg-8">
						<div class="section-tittle text-center mb-55">
							<h2>{{ subject.title }} Courses</h2>
						</div>
					</div>
				</div>
                <div class="courses-actives">
						{% for grade in subject.grades %}
						<div class="properties pb-20">
							<div class="properties__card">
								<div class="properties__img overlay1">
									<img src="{{ grade.image_url }}" alt="">
								</div>
								<div class="properties__caption">
									<p>{{ grade.title }}</p>
										{% for topic in grade.topics %}
										<h3><a href="{{ topic.my_url }}">{{ topic.title }}</a></h3>
										<br>
										{% endfor %}
								</div>
							</div>
						</div>
						{% endfor %}
					 </div>
                </div>
            </div>
			{% endfor %}
			<div class="col-xl-12">
                        <div class="section-tittle text-center mt-20">
                            <a href="{% url 'Home:Courses' %}" class="border-btn">View More Subjects</a>
                        </div>
            </div>
			
        <section class="about-area1 fix pt-10">
            <div class="support-wrapper align-items-center">
                <div class="left-content1">
                    <div class="about-icon">
                        <img src="/media/img/icon/about.svg" alt="">
                    </div>

                    <div class="section-tittle section-tittle2 mb-55">
                        <div class="front-text">
                            <h2 class="">Learn better online with the best content and resources</h2>
                            <p>Content has been gathered from various sources in order to create an
							 experience of simplified learning. Through this platform, you can:</p>
                        </div>
                    </div>
                    <div class="single-features">
                        <div class="features-icon">
                            <img src="/media/img/icon/right-icon.svg" alt="">
                        </div>
                        <div class="features-caption">
                            <p>Find content that matches with your needs easier and more efficiently.</p>
                        </div>
                    </div>
                    <div class="single-features">
                        <div class="features-icon">
                            <img src="/media/img/icon/right-icon.svg" alt="">
                        </div>
                        <div class="features-caption">
                            <p>Gather information from a variety of sources including videos.</p>
                        </div>
                    </div>

                    <div class="single-features">
                        <div class="features-icon">
                            <img src="/media/img/icon/right-icon.svg" alt="">
                        </div>
                        <div class="features-caption">
                            <p>Learn with your peers and share information amongst each other.</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </main>
{% endblock %}